### ISSUE TITLE
BDE图标状态不正确

### ISSUE THREAD

**Issue by thingyfy** [Ewebalvin/ccdos-ios-app#10]
列表、个人档案右上角。

BDE有三种状态：
1. 已经有BDE
2. BDE学习中
3. 未参与BDE

请确认一下

![image](https://user-images.githubusercontent.com/28604416/27927193-fbd5a0b2-6258-11e7-93fa-76c46fda4afe.png)

**Comment by myYunLog** [comment]
已经解决

**Comment by thingyfy** [comment]
BDE学习中的状态不正确
根据student.bde_status判断：
0：未参与BDE
1：BDE学习中
2：已经获得BDE

**Comment by Ewebalvin** [comment]
已经解决。
