### ISSUE TITLE
Skills信息中，每一列中0的不要显示

### ISSUE THREAD

**Issue by thingyfy** [Ewebalvin/ccdos-ios-app#11]

**Comment by myYunLog** [comment]
已近解决

**Comment by myYunLog** [comment]
已经解决
<img width="672" alt="2017-07-07 14 32 20" src="https://user-images.githubusercontent.com/19160933/27945951-eaf81fee-6321-11e7-8746-60bae73b4118.png">

**Comment by thingyfy** [comment]
解决了。
