### ISSUE TITLE
没有BDE的学生，点击右上角BDE icon没有反应

### ISSUE THREAD

**Issue by thingyfy** [Ewebalvin/ccdos-ios-app#17]
应该跳出报读BDE的窗口

![image](https://user-images.githubusercontent.com/28604416/27930370-49a3d93e-6264-11e7-9e5e-2e3d244b0797.png)

**Comment by myYunLog** [comment]
BDE状态和nickname有关联么 我这边是没关系的    bde按钮能不能点击除了状态还有教练是否是当前教练
最好把测试账号也贴出来  我跟踪测试一下

**Comment by myYunLog** [comment]
已经解决

**Comment by myYunLog** [comment]
。。。。。。
