### ISSUE TITLE
日程里面的每个黑点，可以像road map那样，使用空心、实心反应状态码？

### ISSUE THREAD

**Issue by thingyfy** [Ewebalvin/ccdos-ios-app#20]
![image](https://user-images.githubusercontent.com/28604416/27982277-6aed3d8e-636c-11e7-8919-4357ebdf5fa9.png)
![image](https://user-images.githubusercontent.com/28604416/27982280-7dd8aca8-636c-11e7-9421-158d2c1c80c5.png)

**Comment by myYunLog** [comment]
已经解决
