### ISSUE TITLE
Road Map外观调整

### ISSUE THREAD

**Issue by thingyfy** [Ewebalvin/ccdos-ios-app#26]
![image](https://user-images.githubusercontent.com/28604416/27982557-454d9b5e-6372-11e7-8ca8-c2dc7136c0cd.png)

**Comment by thingyfy** [comment]
日期旁边的实心圈要高一点，跟日期的中心对齐。

**Comment by thingyfy** [comment]
看到更新了。
有一点漏了： 日期旁边的**实心圈**要高一点，跟日期的中心对齐。

**Comment by myYunLog** [comment]
不会做   这个就是同一个控件  我只是重新绘制了一遍而已   位置不准确我也不知道是什么问题   我是center.y 相等的

**Comment by myYunLog** [comment]
嗯  已经上调了

**Comment by myYunLog** [comment]
遗漏这个
