### ISSUE TITLE
教练证件：两张图片对调，缺省时需要显示灰度图（汪博提供）

### ISSUE THREAD

**Issue by thingyfy** [Ewebalvin/ccdos-ios-app#35]
![image](https://user-images.githubusercontent.com/28604416/28081312-d4f6af6c-663c-11e7-9bf1-6d0d415493c7.png)

**Comment by thingyfy** [comment]
已经看到对调和更换了图片，但要调整为灰度图

**Comment by myYunLog** [comment]
已经解决
