### ISSUE TITLE
my students搜索功能

### ISSUE THREAD

**Issue by thingyfy** [Ewebalvin/ccdos-ios-app#4]
点击X按钮后，要恢复没有过滤的状态。
（现在只是清楚了输入框中的内容，回不到原始状态）

**Comment by thingyfy** [comment]
对于这个搜索功能，请：
1. 增加driver license number的模糊搜索
2. 输入框提示文字改为：name, telephone, licence number
3. 下面情况下，就触发搜索：
    1）switch发生变化
    2）X按钮
    3）点击了键盘enter

**Comment by thingyfy** [comment]
看到修改。 测试发现有个bug：输入licence number模糊搜索，搜索不到学生

**Comment by myYunLog** [comment]
字段取错了   已经解决

**Comment by Ewebalvin** [comment]
添加了keyword搜索时，再点击开关不起作用
