### ISSUE TITLE
Payment History 的信息要紧凑显示

### ISSUE THREAD

**Issue by thingyfy** [Ewebalvin/ccdos-ios-app#40]
现在如果某项信息缺的情况下会产生残缺的现象。
请按下面的例子来显示：

- $255.00
- BDE Class
- In Vehicle xx Hour(s)
- Road Test xx Time(s)
- (订单备注comment字段）(增加显示这个内容）

后面的4项拼接成带换行的字符串显示，如果某个缺少了，内容往上靠就可以。例如没有BDE Class，就显示为
$255.00
In Vehicle xx Hour(s)
Road Test xx Time(s)
(订单备注comment字段）

![image](https://user-images.githubusercontent.com/28604416/28121762-1b629210-66ea-11e7-9f4f-26ed7b8221cb.png)

**Comment by myYunLog** [comment]
已经解决
