### ISSUE TITLE
Road Map信息里面的IN-VEHICLE改为 In Vehicle; ROAD-TEST改为Road Test （跟payment record表达的一样）

### ISSUE THREAD

**Issue by thingyfy** [Ewebalvin/ccdos-ios-app#41]
![image](https://user-images.githubusercontent.com/28604416/28121953-c661dd56-66ea-11e7-9f95-9a8873617929.png)

**Comment by myYunLog** [comment]
这个需要你们那边来修改   因为我是直接取的你那边的字段

**Comment by thingyfy** [comment]
关系不大，这个不修改了。（因为使用的是credit-type字段，不能修改）
