### ISSUE TITLE
in vehicle预约duration调整

### ISSUE THREAD

**Issue by thingyfy** [Ewebalvin/ccdos-ios-app#42]
以5分钟为基本单位，最多2小时
5 Minutes
10 Minutes
15 Minutes
20 Minutes
25 Minutes
30 Minutes
35 Minutes
40 Minutes
45 Minutes
50 Minutes
55 Minutes
1 Hour
1 Hour 5 Minutes
1 Hour 10 Minutes
1 Hour 15 Minutes
1 Hour 20 Minutes
1 Hour 25 Minutes
1 Hour 30 Minutes
1 Hour 35 Minutes
1 Hour 40 Minutes
1 Hour 45 Minutes
1 Hour 50 Minutes
1 Hour 55 Minutes
2 Hours

duration的存储现在是以小时为单位的，改为以分钟为单位，否则用小数表达不出来35分钟之类的非整数了。

上述对应的duration的值，依次是
5， 10， 15， 20， 25 ......120

**Comment by myYunLog** [comment]
已经解决
