### ISSUE TITLE
拍照功能，点击了X，照片也更新上去了（X是cancel，放弃）

### ISSUE THREAD

**Issue by thingyfy** [Ewebalvin/ccdos-ios-app#43]

**Comment by myYunLog** [comment]
没有更新上去   这只是我截图的临时图    也就是根据这个来截图的   本地也没有保存

**Comment by thingyfy** [comment]
有点误导了，让人觉得已经更换了图片。能不能取消的时候，显示回原来的图？

**Comment by myYunLog** [comment]
难道现在 你那边不是这样子？？？

**Comment by thingyfy** [comment]
之前是截图和签名取消也有缓存的。 也就是可以不必再签名。  现在把这个去掉了。确定后才缓存签名
