### ISSUE TITLE
日期选择器打开的时候，应该跟要设置的字段的值一样。如果没有值才默认为当前时间。

### ISSUE THREAD

**Issue by thingyfy** [Ewebalvin/ccdos-ios-app#44]
![image](https://user-images.githubusercontent.com/28604416/28137020-b7efbf7a-6719-11e7-9a9a-6f14805a20a6.png)

**Comment by myYunLog** [comment]
不会做     日期选择器已经封装了

**Comment by myYunLog** [comment]
jiejue
