### ISSUE TITLE
选择框（日期、时间、自定义选项）打开的时候，默认是当前的值（如果没有，时间默认当前，自定义选项，默认第一个）

### ISSUE THREAD

**Issue by thingyfy** [Ewebalvin/ccdos-ios-app#45]
1. Add payment
    1）pay date
    2）Hours
    3）Times
2. Road Test Result
    1）Test Date（选择后，因为显示多了秒，信息显示不全）
3. + In Vehicle
    1）Date
    2）Start Time（这里打错字了，应该是Start）
    3）Duration（这里10 minutes，30 minutes出来的值不正确）
4. + Road Test
    1）Test Date
    2）Test Class
    3）Start Time（这里打错字，应该是Start）
    4）Duration
5. My Licence
    1）Driver Licence：Issue date， expiry date
    2）Instructor Licence： licence class， issue date，expiry date
    3）municipal Licence: expiry date（在最新版本中，点击选择器没有打开）
6. My Insurrance
    1）Effective Date（这里打错字，应该是Effective）
    2）Expiry Date
7. Road Test Booking（此窗口标题没放正中）
    1）Test Class
    2）Start Time（这里打错字，应该是Start）
    3）Duration

**Comment by myYunLog** [comment]
解决

**Comment by Ewebalvin** [comment]
测试未通过
如下图， 第一次选择2017-10-31日，发现选错了，再要改回2017-10-30日，点击打开应该是2017-10-31日(现在又回到2017-8-31了）
![image](https://user-images.githubusercontent.com/4986240/29927750-416f3522-8e35-11e7-883a-fd4543e6dec8.png)

**Comment by Ewebalvin** [comment]
测试通过。
