### ISSUE TITLE
in-vehicle duration调整为分钟为单位（原来是小时）

### ISSUE THREAD

**Issue by thingyfy** [Ewebalvin/ccdos-ios-app#47]
由于小时无法表达5分钟、10分钟等客户要求的以5分钟为基本单元的时间，in-vehicle duration需要从原来的以小时为单位修改为以分钟为单位。

此调整在iPad App上涉及以下的地方：
1. 日程的结束时间的计算
2. +In Vehicle窗口的duration选择
3. In Vehicle complete窗口的duration选择
4. +Road Test窗口的duration选择
5. Road Test complete窗口的duration选择
6. Road Map显示的In Vehicle记录（Hours 改为 Minutes）
7. Payment Record的In Vehicle信息（Hours改为Minutes）
8. 学生credit， In Vehicle信息的显示，修改为xx hrs xx mins / xx hrs xx mins, （地方受限，请稍微缩短进度条，两个进度条没有对比性，可以长短不一）

**Comment by thingyfy** [comment]
Credit 按如下方式显示（文字往右靠）
![image](https://user-images.githubusercontent.com/28604416/28174301-2a1ed306-67bf-11e7-81b1-313cffc03a11.png)

**Comment by thingyfy** [comment]
In Vehicle结果提交页面初始化的时候Duration：90 Hours
![image](https://user-images.githubusercontent.com/28604416/28271506-b155af92-6ad6-11e7-8af6-87daca023e5e.png)

**Comment by myYunLog** [comment]
解决
