### ISSUE TITLE
离线状况下，在学生档案中添加了考试预约，在book test booking没有反应出来

### ISSUE THREAD

**Issue by Ewebalvin** [Ewebalvin/ccdos-ios-app#50]

**Comment by Ewebalvin** [comment]
请见下面截图。
就算重新恢复连线后，记录也没有刷新出来。（数据库确认有该记录）
![image](https://user-images.githubusercontent.com/4986240/29928566-54ea6d9a-8e37-11e7-8f58-efa366e17248.png)
![image](https://user-images.githubusercontent.com/4986240/29928579-5e295650-8e37-11e7-9a60-39430b63a110.png)

**Comment by Ewebalvin** [comment]
在线情况下也有这种情况

**Comment by myYunLog** [comment]
<img width="643" alt="2017-09-09 14 22 55" src="https://user-images.githubusercontent.com/19160933/30237712-675e4ac0-956a-11e7-973e-fb1ab24dc3ae.png">
刚添加 状态是  -1  所以不会显示出来

**Comment by myYunLog** [comment]
<img width="371" alt="2017-09-09 14 25 28" src="https://user-images.githubusercontent.com/19160933/30237767-5c6a3c5e-956b-11e7-8159-9bf29205ab89.png">
<img width="371" alt="2017-09-09 14 25 28" src="https://user-images.githubusercontent.com/19160933/30237767-5c6a3c5e-956b-11e7-8159-9bf29205ab89.png">

**Comment by myYunLog** [comment]
还没有？

**Comment by Ewebalvin** [comment]
已经有了。passed。
