### ISSUE TITLE
学生驾照拍照后，照片没有传送到服务端（或没有传送成功）

### ISSUE THREAD

**Issue by Ewebalvin** [Ewebalvin/ccdos-ios-app#52]
图片对应的UUID已经更新到学生档案
但图片对应的file记录没有找到、文件夹中也没有对应文件

**Comment by myYunLog** [comment]
如果没有提示错误   那么  接口调用是成功的

**Comment by Ewebalvin** [comment]
学生档案记录对应字段有内容。只是图片没有上传成功，请看看上传是否有错误

**Comment by myYunLog** [comment]
<img width="578" alt="2017-09-04 11 08 29" src="https://user-images.githubusercontent.com/19160933/30010331-80d68bd2-9161-11e7-878e-93ea8a497e69.png">

**Comment by myYunLog** [comment]
这个就是参数   image 是图片

**Comment by myYunLog** [comment]
![2017-09-04 11 30 51](https://user-images.githubusercontent.com/19160933/30010753-a92a93be-9164-11e7-99a4-6b1407ba6055.png)
网上资料 也是这样

**Comment by Ewebalvin** [comment]
那就好。我们关心的是为什么没有成功，分析出问题所在，然后纠正。最终确保整个系统可用。

现在还不知道问题在客户端还是服务端。

请debug一下接口调用结果，看有没有什么异常。

**Comment by thingyfy** [comment]
再次测试，通过。
