### ISSUE TITLE
在线：My Profile提交后，提示成功，但没有更改

### ISSUE THREAD

**Issue by Ewebalvin** [Ewebalvin/ccdos-ios-app#54]
![image](https://user-images.githubusercontent.com/4986240/29929123-aadf8cfc-8e38-11e7-8786-93f0c2fff970.png)

1. 勾选了accept new students，提交，提示成功
2. 再从菜单打开此窗口，显示没有勾选

查看数据库记录，没有更新。

**Comment by myYunLog** [comment]
解决
