### ISSUE TITLE
confirm payment成功后没有刷新列表

### ISSUE THREAD

**Issue by Ewebalvin** [Ewebalvin/ccdos-ios-app#59]
点击了payment record的confirm按钮后，窗口关闭，对应的Payment record没有刷新，还是处于未confirm状态。

**Comment by myYunLog** [comment]
这个问题  比较难解决  因为你们那边关于订单这一块   以前是有问题的    所以增加之后的处理APP都没有做完整   需要时间完成这一块

**Comment by myYunLog** [comment]
解决
