### ISSUE TITLE
Delete an "unpaid" payment提示错误，未知什么原因

### ISSUE THREAD

**Issue by Ewebalvin** [Ewebalvin/ccdos-ios-app#60]
现象请见下图

我尝试过直接调用API，正常调用。请看看是什么原因fail了。
最好能显示一下异常的原因，否则以后运维人员很难跟进处理。谢谢。

![image](https://user-images.githubusercontent.com/4986240/30195040-f5898a4a-9424-11e7-9eb0-2f2300695ac8.png)

**Comment by Ewebalvin** [comment]
![image](https://user-images.githubusercontent.com/4986240/30195103-6e194554-9425-11e7-9b8a-48a3d75e8ca7.png)

**Comment by myYunLog** [comment]
解决

**Comment by myYunLog** [comment]
解决
