### ISSUE TITLE
Road Test Booking点击share出来的月份应该是当前浏览的月份

### ISSUE THREAD

**Issue by Ewebalvin** [Ewebalvin/ccdos-ios-app#62]
例如，我选中了Jul 2017, 然后点击Share按钮，出来的这个图应该就是Jul 2017的情况。

![image](https://user-images.githubusercontent.com/4986240/30195322-bd72d13c-9426-11e7-8521-8120940be4dc.png)

另外，在share的图片中，考场没有显示出来
![image](https://user-images.githubusercontent.com/4986240/30195375-0e934c0e-9427-11e7-8990-05fdf4d1ad49.png)

**Comment by myYunLog** [comment]
<img width="612" alt="2017-09-09 11 01 54" src="https://user-images.githubusercontent.com/19160933/30236535-55a18fc0-954e-11e7-8e74-c3a9914df331.png">
记录选中  地址是有的

**Comment by myYunLog** [comment]
![Uploading 屏幕快照 2017-09-09 11.03.57.png…]()
相册里面也是有的

**Comment by Ewebalvin** [comment]
在左边翻转了日历月份之后，右边应该自动刷新左边日历中选择的日期，否则两边信息不一致。

**Comment by Ewebalvin** [comment]
在新的版本中，返转了月份，不自动选中某一天。
可以，就这么做吧。
