### ISSUE TITLE
payment的排序，要增加，如果是同一天，那就按order_id排序，新的排在前面

### ISSUE THREAD

**Issue by Ewebalvin** [Ewebalvin/ccdos-ios-app#63]
![image](https://user-images.githubusercontent.com/4986240/30218247-8da4a268-9486-11e7-82d4-d882943d68e1.png)

**Comment by myYunLog** [comment]
不会   我只是精确到秒的

**Comment by Ewebalvin** [comment]
不行，不行，因为添加时间是客户端指定的，只指定了日期，所以时分秒都是00：00：00
![image](https://user-images.githubusercontent.com/4986240/30236936-2872519c-94f4-11e7-8502-759808e66e43.png)

**Comment by Ewebalvin** [comment]
已经修改
