### ISSUE TITLE
mock test拍照图片的裁剪尺寸应该是773*1000

### ISSUE THREAD

**Issue by Ewebalvin** [Ewebalvin/ccdos-ios-app#67]

**Comment by myYunLog** [comment]
解决

**Comment by Ewebalvin** [comment]
检查了新版本，这个裁剪比例还不对。

![image](https://user-images.githubusercontent.com/4986240/30392128-d81df950-9889-11e7-97e4-bf91846afce3.png)

**Comment by Ewebalvin** [comment]
对，是超出了1024*768的分辨率了。
要缩小一点，750px * 970px
因为纸竖着才能拍下来，你看哪个是长，哪个是宽吧。

**Comment by myYunLog** [comment]
已经改成 750*970
