### ISSUE TITLE
提交in-vehicle的时候，要补充下面的检查逻辑

### ISSUE THREAD

**Issue by Ewebalvin** [Ewebalvin/ccdos-ios-app#69]
1. 左边的至少要有一个选择了
2. credit不够不允许提交（在线的时候有服务端检查，但离线的时候就检查不到了，所以要加上这个限制）

**Comment by myYunLog** [comment]
解决

**Comment by myYunLog** [comment]
已经增加

**Comment by Ewebalvin** [comment]
1. 左边的至少要有一个选择了
测试还没有看见此检查

**Comment by myYunLog** [comment]
看UI“左边” 不知道什么意思

**Comment by myYunLog** [comment]
1，complete练车时候增加判断（已增加）
2，add invehicle 时判断（已增加）

**Comment by Ewebalvin** [comment]
passed.

**Comment by Ewebalvin** [comment]
后来取消了这个约束
“2，add invehicle 时判断（已增加）”
