### ISSUE TITLE
学生驾照拍照的尺寸有点小，出来的图片很蒙，请放大一倍

### ISSUE THREAD

**Issue by Ewebalvin** [Ewebalvin/ccdos-ios-app#72]
![image](https://user-images.githubusercontent.com/4986240/30401196-5bf903f6-98a7-11e7-928a-c76615d20c0b.png)

**Comment by Ewebalvin** [comment]
请看看，出来的图片为什么那么蒙，好像像素很小一样。

设计要求的尺寸是1050px * 660px，应该很清晰才对。

![image](https://user-images.githubusercontent.com/4986240/30527990-8963f8b6-9bfc-11e7-8700-4e41acbf3c57.png)

**Comment by Ewebalvin** [comment]
裁剪出来的这个图片大小不够
![image](https://user-images.githubusercontent.com/4986240/30555706-46c503b8-9c76-11e7-91c1-0fa42f014c52.png)

**Comment by myYunLog** [comment]
1024*768  的像素    屏幕外的也要裁剪？

**Comment by myYunLog** [comment]
210 *132    放大5倍   屏幕裁剪不了  修改成放大4倍 像素（1024 *768）

**Comment by thingyfy** [comment]
sorry, 没有考虑到，超出屏幕大小。
定为875*550吧
