### ISSUE TITLE
Municipal Licence 没有弹出选择照片或拍照的小按钮

### ISSUE THREAD

**Issue by Ewebalvin** [Ewebalvin/ccdos-ios-app#74]
![image](https://user-images.githubusercontent.com/4986240/30402006-434144f6-98aa-11e7-8eb5-9905c3de8c48.png)

**Comment by myYunLog** [comment]
<img width="1120" alt="2017-09-18 10 39 22" src="https://user-images.githubusercontent.com/19160933/30527700-179ec4ba-9c5e-11e7-9ab3-b07f39c3541f.png">

**Comment by Ewebalvin** [comment]
点击新增后，应该自动进入编辑状态

**Comment by Ewebalvin** [comment]
已经修改。
