### ISSUE TITLE
修改密码，保存失败；没有显示原因；键盘弹起，内容上移了，窗口不动，导致错位了

### ISSUE THREAD

**Issue by Ewebalvin** [Ewebalvin/ccdos-ios-app#77]
![image](https://user-images.githubusercontent.com/4986240/30555379-6d6811dc-9c75-11e7-8e5f-0225a8bec823.png)
![image](https://user-images.githubusercontent.com/4986240/30555393-7547c334-9c75-11e7-8036-9febb1cf8f14.png)

![image](https://user-images.githubusercontent.com/4986240/30555418-8018b55c-9c75-11e7-9a52-dcb2fbfd67aa.png)

**Comment by myYunLog** [comment]
<img width="306" alt="2017-09-19 11 06 13" src="https://user-images.githubusercontent.com/19160933/30574138-9fe4abec-9d2a-11e7-8a42-84ed1e88af7d.png">

**Comment by myYunLog** [comment]
不清楚什么原因  我收到的数据是bad request

**Comment by Ewebalvin** [comment]
从返回的数据看，应该调用的不是同一个接口，请跟下图对比确认一下
![image](https://user-images.githubusercontent.com/4986240/30612563-02458d10-9d53-11e7-9b03-94a98f03f735.png)
